apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer
