apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: final
type: Opaque
data:
  MYSQL_USERNAME: <base64-encoded-username>
  MYSQL_PASSWORD: <base64-encoded-password>

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: final
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <base64-encoded-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-secret-key>

---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-image-pull-secret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config-json>
